from __future__ import annotations

import re

_KNOWN: dict[str, str] = {
    "Coordination Chemistry Reviews": "Coord. Chem. Rev.",
    "Chemical Reviews": "Chem. Rev.",
    "Chemical Society Reviews": "Chem. Soc. Rev.",
    "Chemical Communications": "Chem. Commun.",
    "Journal of the American Chemical Society": "J. Am. Chem. Soc.",
    "Angewandte Chemie International Edition": "Angew. Chem. Int. Ed.",
    "Angewandte Chemie": "Angew. Chem.",
    "Nature Chemistry": "Nat. Chem.",
    "Nature Materials": "Nat. Mater.",
    "Nature Catalysis": "Nat. Catal.",
    "Nature Communications": "Nat. Commun.",
    "Nature Energy": "Nat. Energy",
    "Nature Reviews Chemistry": "Nat. Rev. Chem.",
    "Nature Reviews Materials": "Nat. Rev. Mater.",
    "Advanced Materials": "Adv. Mater.",
    "Advanced Functional Materials": "Adv. Funct. Mater.",
    "Advanced Energy Materials": "Adv. Energy Mater.",
    "ACS Catalysis": "ACS Catal.",
    "ACS Nano": "ACS Nano",
    "ACS Applied Materials & Interfaces": "ACS Appl. Mater. Interfaces",
    "ACS Energy Letters": "ACS Energy Lett.",
    "ACS Central Science": "ACS Cent. Sci.",
    "ACS Sustainable Chemistry & Engineering": "ACS Sustainable Chem. Eng.",
    "Chemistry of Materials": "Chem. Mater.",
    "Inorganic Chemistry": "Inorg. Chem.",
    "Organic Letters": "Org. Lett.",
    "Journal of Organic Chemistry": "J. Org. Chem.",
    "Journal of Physical Chemistry A": "J. Phys. Chem. A",
    "Journal of Physical Chemistry B": "J. Phys. Chem. B",
    "Journal of Physical Chemistry C": "J. Phys. Chem. C",
    "Journal of Physical Chemistry Letters": "J. Phys. Chem. Lett.",
    "The Journal of Physical Chemistry A": "J. Phys. Chem. A",
    "The Journal of Physical Chemistry B": "J. Phys. Chem. B",
    "The Journal of Physical Chemistry C": "J. Phys. Chem. C",
    "The Journal of Physical Chemistry Letters": "J. Phys. Chem. Lett.",
    "Physical Review Letters": "Phys. Rev. Lett.",
    "Physical Review B": "Phys. Rev. B",
    "Physical Chemistry Chemical Physics": "Phys. Chem. Chem. Phys.",
    "Journal of Materials Chemistry A": "J. Mater. Chem. A",
    "Journal of Materials Chemistry B": "J. Mater. Chem. B",
    "Journal of Materials Chemistry C": "J. Mater. Chem. C",
    "Journal of the European Ceramic Society": "J. Eur. Ceram. Soc.",
    "Journal of the American Ceramic Society": "J. Am. Ceram. Soc.",
    "Journal of Catalysis": "J. Catal.",
    "Applied Catalysis B: Environmental": "Appl. Catal. B",
    "Applied Catalysis A: General": "Appl. Catal. A",
    "Catalysis Today": "Catal. Today",
    "Catalysis Science & Technology": "Catal. Sci. Technol.",
    "Dalton Transactions": "Dalton Trans.",
    "Green Chemistry": "Green Chem.",
    "Journal of Alloys and Compounds": "J. Alloys Compd.",
    "Acta Materialia": "Acta Mater.",
    "Scripta Materialia": "Scr. Mater.",
    "Materials Science and Engineering: A": "Mater. Sci. Eng. A",
    "Materials Science and Engineering: B": "Mater. Sci. Eng. B",
    "Materials Research Letters": "Mater. Res. Lett.",
    "Ceramics International": "Ceram. Int.",
    "Journal of Non-Crystalline Solids": "J. Non-Cryst. Solids",
    "Journal of Sol-Gel Science and Technology": "J. Sol-Gel Sci. Technol.",
    "Journal of the Ceramic Society of Japan": "J. Ceram. Soc. Jpn.",
    "Journal of Materials Science": "J. Mater. Sci.",
    "International Journal of Hydrogen Energy": "Int. J. Hydrogen Energy",
    "Electrochimica Acta": "Electrochim. Acta",
    "Journal of Power Sources": "J. Power Sources",
    "Journal of the Electrochemical Society": "J. Electrochem. Soc.",
    "Nano Letters": "Nano Lett.",
    "Nano Energy": "Nano Energy",
    "Nanoscale": "Nanoscale",
    "Small": "Small",
    "Chemical Engineering Journal": "Chem. Eng. J.",
    "Science": "Science",
    "Nature": "Nature",
    "Proceedings of the National Academy of Sciences": "Proc. Natl. Acad. Sci. U.S.A.",
    "Scientific Reports": "Sci. Rep.",
    "Energy & Environmental Science": "Energy Environ. Sci.",
    "Environmental Science & Technology": "Environ. Sci. Technol.",
    "ChemSusChem": "ChemSusChem",
    "ChemCatChem": "ChemCatChem",
    "Chemistry – A European Journal": "Chem. Eur. J.",
    "Chemistry - A European Journal": "Chem. Eur. J.",
    "European Journal of Inorganic Chemistry": "Eur. J. Inorg. Chem.",
    "Langmuir": "Langmuir",
    "Microporous and Mesoporous Materials": "Microporous Mesoporous Mater.",
    "Journal of Membrane Science": "J. Membr. Sci.",
    "Carbon": "Carbon",
    "Composites Part B: Engineering": "Compos. B Eng.",
    "Polymer": "Polymer",
    "Macromolecules": "Macromolecules",
}

_LTWA: list[tuple[str, str]] = [
    ("journal", "J."),
    ("american", "Am."),
    ("chemical", "Chem."),
    ("chemistry", "Chem."),
    ("physical", "Phys."),
    ("physics", "Phys."),
    ("society", "Soc."),
    ("international", "Int."),
    ("european", "Eur."),
    ("review", "Rev."),
    ("reviews", "Rev."),
    ("letters", "Lett."),
    ("communications", "Commun."),
    ("communication", "Commun."),
    ("engineering", "Eng."),
    ("materials", "Mater."),
    ("material", "Mater."),
    ("science", "Sci."),
    ("sciences", "Sci."),
    ("technology", "Technol."),
    ("applied", "Appl."),
    ("advanced", "Adv."),
    ("functional", "Funct."),
    ("organic", "Org."),
    ("inorganic", "Inorg."),
    ("analytical", "Anal."),
    ("environmental", "Environ."),
    ("catalysis", "Catal."),
    ("ceramic", "Ceram."),
    ("ceramics", "Ceram."),
    ("crystalline", "Cryst."),
    ("electrochemical", "Electrochem."),
    ("compounds", "Compd."),
    ("alloys", "Alloys"),
    ("coordination", "Coord."),
    ("computational", "Comput."),
    ("theoretical", "Theor."),
    ("experimental", "Exp."),
    ("sustainable", "Sustainable"),
    ("national", "Natl."),
    ("academy", "Acad."),
    ("proceedings", "Proc."),
    ("transactions", "Trans."),
    ("research", "Res."),
    ("progress", "Prog."),
    ("reports", "Rep."),
    ("annals", "Ann."),
    ("bulletin", "Bull."),
    ("membranes", "Membr."),
    ("membrane", "Membr."),
    ("composites", "Compos."),
    ("polymer", "Polym."),
    ("surface", "Surf."),
    ("surfaces", "Surf."),
    ("energy", "Energy"),
    ("hydrogen", "Hydrogen"),
    ("microporous", "Microporous"),
    ("mesoporous", "Mesoporous"),
    ("molecular", "Mol."),
    ("supramolecular", "Supramol."),
    ("biological", "Biol."),
    ("biomedical", "Biomed."),
    ("japanese", "Jpn."),
    ("japan", "Jpn."),
    ("general", "Gen."),
]

_SKIP = {"the", "of", "and", "in", "on", "for", "a", "an", "&", "–", "-", ":", "part"}

_ltwa_map = {word: abbr for word, abbr in _LTWA}


def abbreviate_journal(full_name: str) -> str:
    key = full_name.strip()
    if key in _KNOWN:
        return _KNOWN[key]

    words = re.split(r"\s+", key)
    result = []
    for w in words:
        lower = w.lower().rstrip(",;:")
        if lower in _SKIP:
            continue
        abbr = _ltwa_map.get(lower)
        if abbr:
            result.append(abbr)
        else:
            result.append(w)
    abbreviated = " ".join(result)
    if abbreviated == full_name:
        return full_name
    return abbreviated
